### ISSUE TITLE
shortcut to run current package?

### ISSUE THREAD

**Issue by llooz** [joefitzgerald/go-plus#154]
Is there a way to run the current package with a shortcut or something like that?

**Comment by joefitzgerald** [comment]
Not currently, but this would be nice. Happy to accept a PR. The primary issue is display of the program's output.

**Comment by joefitzgerald** [comment]
We now have a way to display program output (in the `go-plus` panel), but is this still desirable?

**Comment by fabstu** [comment]
Would be nice to run a gui program this way, so desireable for me.

**Comment by fabstu** [comment]
It's possible to run programs with platformio-ide-terminal in the console.

**Comment by lloiser** [comment]
Because it's a terminal in atom. There are bunch of packages out there to one in atom: https://atom.io/packages/search?utf8=%E2%9C%93&q=keyword:terminal

Beside that having this integrated into `go-plus` is definitely a nice feature. Although I think it's not easy to implement. Here are some points to consider if someone is ever doing this:

* specify the package to run
* how to run? `go build`? (looking at [gb](https://getgb.io/) and tools like it there)
* args and flags
* set some additional environment variables
* current working dir
* display stdout/stderr
* provide stdin
* ... just to name a few problems, definitely more to come

It seems easy at first glance but definitely takes quite some effort.
