### ISSUE TITLE
List all available packages

### ISSUE THREAD

**Issue by carlosbrando** [joefitzgerald/go-plus#161]
GoSublime has this list that you can use to add and delete packages. I see this as an important addition to this awesome package as well.

![screen shot 2015-02-26 at 14 04 02](https://cloud.githubusercontent.com/assets/2035/6396981/93166c26-bdc0-11e4-9146-bd74d513ca49.png)

**Comment by joefitzgerald** [comment]
`goimports` largely obviates the need for this...

**Comment by carlosbrando** [comment]
Yeah, but to `goimports` do its job it's necessary to remember the name of the package and the exact name of the function you are looking for without using the autocomplete function.

Is it possible to autocomplete suggest possible imports when autocomplete fails to find a match?

**Comment by joefitzgerald** [comment]
This sounds like a great use case for an autocomplete-plus provider, that can help you with defining packages. It would only return suggestions when inside an import block. We might need to adjust the grammar to explicitly define when you are importing. Right now I see the cursor having the following scope inside an punctuation.definition.string.end.goimport("...")` or `import ""` block: `punctuation.definition.string.end.go`, so that would be an easy thing to check initially.

**Comment by firstrow** [comment]
autocomplete imports - must have.

**Comment by marconi** [comment]
+1 to this, I miss this coming from `GoSublime`

**Comment by fmpwizard** [comment]
another +1 for a similar functionality to goSublime, I had to disable `goimport` because here and there it would lock up Atom (On fedora 20, 64bit , atom 1.0.2 go-plus 3.4.1), so now I have gofmt to format my files, and manually add imports. Other than this, go-plus is awesome!

**Comment by geovanisouza92** [comment]
+1

**Comment by mastercactapus** [comment]
+1 the most useful part IMO is being able to add/remove imports without losing my place in the current file, it's hard to go back to that :)

**Comment by VitalySenko** [comment]
+1 That would be cool!

**Comment by arlimus** [comment]
+1, the auto-completion of imports from goimports doesn't always get it right. when it fails, the goimports-on-save becomes a real annoyance ;) go sublime was great with the package selection feature

**Comment by zmb3** [comment]
Closing as this functionality is covered in #226
