### ISSUE TITLE
Autocomplete triggering on comma

### ISSUE THREAD

**Issue by philk** [joefitzgerald/go-plus#177]
You can't really see my cursor in this screenshot but it's right after I type the comma that the autocomplete window pops up. Annoying mainly because I so often want to hit enter to go to the next line right after typing a comma (instead I get an arbitrary autocomplete).

![screen shot 2015-03-26 at 3 25 42 pm](https://cloud.githubusercontent.com/assets/29562/6858518/6f3bd1e8-d3cc-11e4-849f-4d00d5e33448.png)

**Comment by philk** [comment]
Relevant change in [autocomplete-plus](https://github.com/atom-community/autocomplete-plus/issues/341#issuecomment-86750262)

**Comment by joefitzgerald** [comment]
Well considering I implemented this in autocomplete-plus (to accommodate another grammar), I should have expected a need to suppress go-plus suggestions as a countermeasure :wink:. I think you're right, we should maintain a blacklist of characters (or prefixes) for which we suppress autocomplete. 

I think this should be a configurable list, so that the user can suppress other character(s) if they desire.

**Comment by philk** [comment]
Agreed, that probably means my PR #178 is too simplistic a fix and the real solution is way outside the realm of my Atom and coffeescript knowledge. Might try to learn something new and take a look over the weekend if I get a chance.

**Comment by philk** [comment]
Ok, making it configurable wasn't actually that hard. I don't like forcing ` ` to be excluded but I couldn't come up with any reason why you'd want autocomplete to trigger on space and adding it to a space delimited list was...well yeah. Updated #178

**Comment by zmb3** [comment]
Would there be any value in having a configurable "opt-in" list or regex (instead of the "opt-out" list of characters to suppress?

Personally I think I'd like to be able to trigger _only_ on `.` or `,` (or manually via ctrl+space).  Sometimes I feel like invoking gocode for each keystroke is overkill.

**Comment by joefitzgerald** [comment]
@zmb3: you can disable auto-activation for autocomplete-plus. In my experience, most people are fine with auto-activation (provided typing performance isn't impacted).

So no, I won't switch to an opt-in list or regex, but I'm fine having a list or regex that can be used to suppress activation which could be used to achieve precisely what you want (by including everything other than the characters you wish to have for activation).

**Comment by zmb3** [comment]
I'm still seeing autocomplete-plus suggestions even for suppressed characters.  My suppressed characters setting is `), space, ;, :, comma, /`.  Using Atom 0.192.0, Go Plus 3.3.6, Autocomplete Plus 2.10.0, on Windows.

![image](https://cloud.githubusercontent.com/assets/7527103/7215989/cf397144-e5bb-11e4-9d4f-937433a8b860.png)

**Comment by svanharmelen** [comment]
@zmb3 PR #180 fixes a problem that causes this... But I'm adding an additional feature to that PR which let's you check a boolean to suppress all non word characters. So I hope the PR will be open for another day (until I got time to commit the update) after which it can be merged to fix the current autocomplete bug...
