### ISSUE TITLE
Auto indent behavior with closures

### ISSUE THREAD

**Issue by anweiss** [joefitzgerald/go-plus#181]
I'm noticing that if I write a function closure and create a new line with my closing curly brace and parend, it auto indents the characters as shown below:

```go
test.handle(a, func() {

    })
```

Is there a way I can configure this package to not do this? Granted, while saving the file will execute gofmt and fix this for me, it's still a bit of a nuisance when writing code.

**Comment by joefitzgerald** [comment]
This likely has nothing to do with go-plus and is instead caused by either the language-go grammar or the bracket-matched package. To verify, disable go-plus, and try to reproduce. If it can only be reproduced while go-plus is enabled, then it's an issue with this package. If it's reproducible when go-plus is disabled, perform the same action of trying to rule in/out the language-go package and the bracket-matches package. Then, once you've identified the oackage causing the issue, open an issue there.

**Comment by joefitzgerald** [comment]
See also: https://github.com/atom/language-go/issues/31#issuecomment-90877896
