### ISSUE TITLE
Function Seperators

### ISSUE THREAD

**Issue by hink** [joefitzgerald/go-plus#191]
Is it possible to add an option for function separators -- a horizontal rule between functions/structs/interfaces?

**Comment by joefitzgerald** [comment]
@hink that seems a bit orthogonal to the purpose of this package, but help me understand what this would look like with a screenshot.

**Comment by hink** [comment]
Sure thing -- The idea is to assist in quickly identifying blocks of code.
![Pycharm Example](http://i.imgur.com/LhsRGIE.png)

**Comment by joefitzgerald** [comment]
@hink This problem is generic and solvable for all grammars (`language-go` being just one of them). It sounds like a good idea for a new package for Atom.

You might want to ask a question in https://discuss.atom.io (supplying that screenshot) asking if anyone has already done this, and if not how you might go about building a package to achieve that user experience.

**Comment by dansouza** [comment]
@hink so did you ever figure this out?
