### ISSUE TITLE
Switch To Use gometalinter

### ISSUE THREAD

**Issue by soygul** [joefitzgerald/go-plus#213]
https://github.com/alecthomas/gometalinter

Just seeking to understand if this is a popular tool with the community. Given that it normalizes output from all known linters, can make linter editor integrations less manual.

**Comment by joefitzgerald** [comment]
Indeed. I think gometalinter is great. I am going to be revisiting the way we run all the tools we use and integrate with https://github.com/atomlinter/linter. As part of this, I will look into the use of gometalinter.

**Comment by soygul** [comment]
:+1:

**Comment by rtyer** [comment]
:+1:

**Comment by adamclerk** [comment]
:thumbsup:

**Comment by santagada** [comment]
Great, have messages integrated with the line of the problem is way better than having them on a tool box, and the metalinter is the way to go for performance and completeness reasons.

Can other people send pull requests for this or is anyone active in fixing this?

**Comment by steelbrain** [comment]
For the DIY people on here, it's super-simple to write a linter, see https://github.com/atom-community/linter/wiki/Linter-API and https://github.com/atom-community/linter/wiki/Migrating-to-the-new-API

**Comment by joefitzgerald** [comment]
This is pending a rewrite of the core runtime detection in https://github.com/joefitzgerald/go-runtime, so that we don't end up with a litany of different ways this is done. While it's trivial to write a linter it is very non trivial to do so in a way that a user has a zero configuration experience based on their current environment. go-runtime will also pave the way for gb and the GO15VENDOREXPERIMENT.

**Comment by santagada** [comment]
Thank you @steelbrain I will look into that. @joefitzgerald go-runtime doesn't look very promising seeing that it hasn't been any commits for 5 months right? Is there anything we can help you with that then?

**Comment by joefitzgerald** [comment]
@santagada it's because I haven't pushed the code that I have locally. For a period of time I was blocked on waiting for package-sets to be included in core (as I was the committer) but recently I decided to move ahead without package-sets as its such a large piece of work it will take time to ship. I will push new code there tomorrow, and I'd welcome the assistance.

**Comment by santagada** [comment]
@joefitzgerald any news?

**Comment by mishak87** [comment]
Any progress?
Linter API evolved quite a bit and maybe writing own package for go linting would be best way to go.

**Comment by joefitzgerald** [comment]
Yep. https://atom.io/packages/gometalinter-linter.

**Comment by mishak87** [comment]
@joefitzgerald Sorry I must have missed it :smile:. I promise I will do lot of user testing.

**Comment by AlbinOS** [comment]
Hello,

I'm using [gometalinter](https://atom.io/packages/gometalinter-linter) and [goplus](https://github.com/joefitzgerald/go-plus) mainly for the autocompletion and the auto formatting capabilities. It works great but a little bit cumberstone to configure. Since you both maintain those packages, do you intend to use gometalinter as the provider for goplus ? Or to include autocompletion and autoformat capabilities to gometalinter ?

Thanks a lot for the great work !

**Comment by joefitzgerald** [comment]
@AlbinOS, yes, gometalinter-linter will replace built-in listing functionality. Autocomplete will be done via autocomplete-go, and formatting will be done via another package too.

**Comment by joefitzgerald** [comment]
This was shipped in `go-plus` `v4.0.0`. Please update to `go-plus` `v4.1.0`.
