### ISSUE TITLE
Clicking on an issue in the messages panel closes the panel

### ISSUE THREAD

**Issue by Eloff** [joefitzgerald/go-plus#243]
I see there are half a dozen issues (ok a dozen) when I save my go file, but if I click on one, the panel is closed. It would be nice if it stayed open once I click on it, so that I can work through the list.

I'm new to Atom, so I apologize if there is a way to keep it open that I'm unaware of.

**Comment by Eloff** [comment]
I see it only happens when the issue clicked on is in a different file than the currently displayed one. That's something at least, but it would be nice if it stayed open between file switches.

**Comment by joefitzgerald** [comment]
I am going to close this as won't fix - not because this is not desirable, but because I am moving to use of linter, and that will address issue display once complete. Consequently, I don't think I will spend the time to fix this with the existing message panel.

Thanks for the issue report, though! I hope you're enjoying go-plus otherwise :smile:.
