### ISSUE TITLE
Add default build / test flag support

### ISSUE THREAD

**Issue by derekperkins** [joefitzgerald/go-plus#308]
I have a few different build types depending on my target environment, set using build flags. I'd like to be able to specify a default build flag that gets used for testing. You already have inputs for Format, Lint and Vet arguments, so I'd imagine adding a new input for Build arguments and Test arguments, just like the other three.

**Comment by joefitzgerald** [comment]
Take a peek at the following to see the direction I am headed in:

* [environment](https://atom.io/packages/environment): Gives you a sane environment on OS X even if you forget to launch atom from the terminal (e.g. via Dock, Spotlight, Finder, open, etc.)
* [go-config](https://atom.io/packages/go-config): Provides a core package that all other go packages use to determine the correct go runtime, tools, gopath, etc. for a given file, directory, or project in Atom
* [gometalinter-linter](https://atom.io/packages/gometalinter-linter): Integrates [linter](https://atom.io/packages/linter) with [gometalinter](https://github.com/alecthomas/gometalinter)
* [autocomplete-go](https://atom.io/packages/autocomplete-go): An [autocomplete-plus](https://atom.io/packages/autocomplete-plus) provider that uses [gocode](https://github.com/nsf/gocode)

These are not ready for daily use yet, but do function. I still need to add functionality to fetch tools if missing, support .editorconfig, and automatically install required packages. In order to fully turn go-plus into an "installer" of "packages known to work well together" I still have to address:

* Visualization of test coverage (which really should also show test failures)
* Fetching of required tools
* Migrate go-plus configuration to individual packages
* Create a godef package
* Create a build package

If you want to create the build package, then I'm all for it. You could integrate https://atom.io/packages/build and https://atom.io/packages/go-config to achieve a good outcome?

**Comment by joefitzgerald** [comment]
Related: #281

**Comment by derekperkins** [comment]
I love where you're headed. I don't have time to code that at the moment, but I'm more than happy to test things out and give feedback.
