### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by tj** [joefitzgerald/go-plus#350]
I haven no clue what changed, woke up, opened Atom and it no longer works. I didn't update anything go-related (GOPATH etc is all the same) or anything else in Atom. Any suggestions for where to start digging?

**Comment by tj** [comment]
Weird it seems to work with some packages and not others, stdlib seems fine, some in GOPATH are fine, some are not

**Comment by tj** [comment]
looks related, checking out its debug info

**Comment by joefitzgerald** [comment]
@tj you might want to do the following:

1. `gocode set autobuild truer
1. (Close Atom and Sublime)
1. `gocode drop-cache`
1. `gocode close`
1. Open Atom

GoSublime bundles its own version of gocode; it doesn't use the binary you've installed in your `PATH` (likely `$GOPATH/bin/gocode`). If you open GoSublime then it is possible that requests made by Atom will be fulfilled by the daemonized gocode launched by Sublime, and things could get out of whack. Let me know if this helps at all? /cc @nsf.

**Comment by nsf** [comment]
I don't recommend using autobuild feature, just build stuff yourself if that's not a problem. If it is and you hate me, try autobuild it might work for you, but it might not.

Doing `gocode drop-cache` and `gocode close` is pointless. Gocode doesn't store anything on disk, just closing it is enough to drop the cache.

**Comment by joefitzgerald** [comment]
@nsf thanks for clarifying drop-cache functionality.

The autobuild option seems to resolve issues for many go-plus users working in multiple packages (which is most people).

Your comments about it make me wonder what to do about the current functionality. I do run go build to check for syntax issues, but the results are thrown away to avoid binary pollution in the package directory. 

This functionality will be replaced by https://atom.io/packages/gometalinter-linter (gometalinter uses gotype).

This leads me to think that I do need to build some form of build hook (run on save, perhaps) into https://atom.io/packages/autocomplete-go to keep things fresh. To date, I've been relying on autobuild and it being a somewhat reliable thing. Why do you advise against its use?

**Comment by nsf** [comment]
Well, I don't recommend using it, because I haven't tested it myself. Personally I use `gb`, so for me gocode's autobuild doesn't work at all. I think "binary polution" as you call it is okay, because that's what autobuild does, autobuild is not some fancy in-memory build. In atom one can use https://github.com/noseglid/atom-build with `go install` as a command just fine.

So, there. I don't know, if autobuild works for you, great, I just can't say anything about its implementation. Autobuild is essentially the same as running `go install`, so I see little value in this feature. Just run `go install` or `gb build` if you prefer `gb`.

I wrote an issue in gocode where I talk about rewriting gocode. The proper solution to this problem will be parsing source files on the gocode side instead of compiled packages. But that's tricky and I have no time to implement it.

**Comment by joefitzgerald** [comment]
> I think "binary polution" as you call it is okay, because that's what autobuild does, autobuild is not some fancy in-memory build.

I was referring to the use of [`go build -o`](https://github.com/joefitzgerald/go-plus/blob/7cb18fdf0d46e1c88b8fda50edfafcf693bdedfe/lib/gobuild.coffee#L82) to redirect the binary output. I acknowledge that it's probably better to use `go install` (or some other configurable command) going forward.

**Comment by tj** [comment]
It's not a huge deal after understanding gocode more. I figured it was working from source but this issue made sense after reading more about it, I've been doing nothing but cross-compiles.
