### ISSUE TITLE
showing an error/warning panel instead of inline error markers?

### ISSUE THREAD

**Issue by yyoon** [joefitzgerald/go-plus#425]
I don't know when this happened exactly, but recently the go-plus plug-in changed the behavior of showing the compile / lint errors inline with the code instead of showing them in a separate output panel.

I really want the previous behavior back. It was a lot easier to see all the errors in different locations in that one panel, and now I have to scroll through all the files to manually fine all the places.

Is there an easy way to get the error output panel back again?

**Comment by joefitzgerald** [comment]
I am working to add this back to the package.

**Comment by lloiser** [comment]
All errors/warnings are shown in the [linter](https://github.com/steelbrain/linter/tree/v1.11.21) panel for a while now. The linter package shows the errors both inline and in a separate panel at the bottom of atom (which can be resized and toggled).

**Comment by yyoon** [comment]
Yeah, I can confirm that. I'll close this.

**Comment by jspiro** [comment]
It's been a while since I've written Go in Atom and I have things mostly working again, but I forget if showing errors inline is supposed to work, or was that removed?

I get syntax errors in the `Test` panel and they correctly hyperlink. I'd really like to also see them inline while I type (or at least after I save), since they're faster to fix immediately after you make them :)

**Comment by zmb3** [comment]
To see errors inline when you save you need to install the linter package and it's dependencies.
