### ISSUE TITLE
Can we make delve optional?

### ISSUE THREAD

**Issue by davidjpeacock** [joefitzgerald/go-plus#469]
Hey there,

I love 99% of the functionality of go-plus for Atom but I really don't like having delve as a requirement.

Please can this be made optional?  I tried to simply remove go-debug but upon restarting Atom it gets pulled right back in, then asks me to install a binary from some random website.

I strongly dislike this. :-)

Please consider making this optional, or if it is already, educate me.

Thank you.

David

**Comment by joefitzgerald** [comment]
Hey @davidjpeacock, I totally understand why people might want to **not** use parts of the functionality that go-plus provides. In fact, the move to having single responsibility packages was done specifically to allow this to happen! 

Right now, the mechanism to support what you're asking for is to just disable the go-debug package (that is, it would be "installed", but not "enabled"). This means it will not be loaded, and will not occupy any resources on your machine other than the disk space associated with having the package installed.

I can completely empathize with the feelings you're having about not being able to uninstall a package that you don't want to use!! Getting into a fight with go-plus about uninstalling is not something I want anyone to have to experience, so I'm going to make changes to enable this to happen, and also to let people make decisions about installing new packages (e.g. by allowing choice).

So, I hope this workaround (using disable instead of uninstall) is acceptable in the short term while I improve the user experience associated with go-plus.

**Comment by davidjpeacock** [comment]
Wow @joefitzgerald!  Right on.

Thank you so much for your understanding and consideration.  I greatly appreciate your sentiment and response here.

FWIW, go-plus is absolutely fantastic, and combined with Atom (obviously) makes for my favourite Golang dev env.

Thank you very much indeed for your work.

David

**Comment by davidjpeacock** [comment]
...Had to follow up.  You, Sir, are awesome.  Did you know that?  People like you are the essence of exemplary OpenSource, and I salute you.

Thank you.  The world needs a lot more of you.

**Comment by joefitzgerald** [comment]
This is fixed in `go-plus` `v5.0.0`.
