### ISSUE TITLE
add a setting to turn off code coverage

### ISSUE THREAD

**Issue by ssoroka** [joefitzgerald/go-plus#496]
Mostly the coloring is driving me nuts. I'd also settle for a less obtrusive coloring option (like gutter-only).

**Comment by joefitzgerald** [comment]
This is already possible. Go to tester-go package preferences. It is worth mentioning that these settings will soon all be located in the go-plus settings page for precisely this reason: they weren't obvious to you.

Also worth mentioning: if the coverage highlighting is driving you nuts, maybe try adding tests instead of turning off the reminder that you haven't covered large portions of your code base?

**Comment by ssoroka** [comment]
Thanks :) 

Half my code coverage from integration tests (outside of go tests) aren't being represented properly, so .. I'll have to look into fixing that.
