### ISSUE TITLE
No `on the fly documentation` available?

### ISSUE THREAD

**Issue by JeromeDesseaux** [joefitzgerald/go-plus#507]
Hi!

First of all, thanks for this awesome job you've done making this greatful extension! 

I don't know if I ask this question in the right place but: Is this possible to get documentation when I my cursor is over a variable/function (Getting its type if it's a variable, or its signature for a function for example) ? 

Thank you in advance :)

**Comment by zmb3** [comment]
This functionality is available with the godoc package. Simply run the
golang:showdoc command (bound to alt +D by default) and observe the doc in
the reference tab of the go plus panel.

**Comment by JeromeDesseaux** [comment]
Thanks for answering :) 

Anyway, it is not as "userfriendly" as poping this documentation over the mouse cursor on the fly. Do you know if there is an option or something? 

Thank you again for this part of answer :)

**Comment by zmb3** [comment]
For now if you want doc you must use the keyboard shortcut.

You may also be interested in Go-signature-statusbar which shows the
signature for the fund under the cursor at all times.

Showing doc with a mouse hover is in the roadmap.

**Comment by JeromeDesseaux** [comment]
Thanks! This does the trick waiting for this feature :)

**Comment by fasa123** [comment]
To be honest this is not a workaround at all. The cursor has to exactly be on the function you want to see the definition of afterwards you have to press the shortcut. Meaning if you are in the parenthesis of a method (which you will be roughly 90% of the time since that's how you check them by entering them from the autocomplete...) you have to go out of the parenthesis and then after checking the docs go back into it which is a huge huge time waste seeing how often this happens. If the docs get shown as a tooltip you wouldn't even come into this situation since you would get the docs shown prior to even writing (and thus choosing) the method.
