### ISSUE TITLE
Navigate to failed test

### ISSUE THREAD

**Issue by r03** [joefitzgerald/go-plus#550]
If a test fails, this is shown nicely in the test panel.
But is there an easy way to navigate to that failed test?
I was expecting that I could click on that error to jump to the correct file/position, but that doesn't work.

**Comment by eduncan911** [comment]
The way I imagine this working (that is usable) is to parse the Test output for the error, and Hyperlink it to the file.

The problem with that analogy is not all failed test are parsable with the `go test` output.  For example, `t.Fail()` doesn't return anything:

```
$ go test -run TestFail
--- FAIL: TestFail (0.00s)
FAIL
exit status 1
```

Therefore, the only way this can work with that output is to parse the `functional name`, and some how search-and-link to it within the testing packages folders?  That's a lot of work.

Fatal()s are easier to find though:

```
$ go test -run TestFatal
--- FAIL: TestFatal (0.00s)
        podcast_test.go:70: it choked
FAIL
exit status 1
```

If file is already open in a tab, focus the tab and jump to line # in the test.

If file is not open, open in new tab, and jump to line # in the test.

But the problem is if using a testing package, like `testify/assert`.  It's output is vastly different depending on which assertion you are using:

```
$ go test -run TestFatal
--- FAIL: TestFatal (0.00s)
        Error Trace:    podcast_test.go:70
        Error:          Should be true
        Messages:       it choked
FAIL
```

But hey, there's that **Test Name** again.  

To me, this would mean the editor will need to keep track of all Test Names throughout all the open folders, in order to parse them for this single test name.  

This is possible with `grep`, using grep to -R recursive search; but, that would not be compatible with Windows machines.

**Comment by r03** [comment]
I'm not a big vim user, but the test results seem to go to the quickfix windows where I can navigate to the failing test. (vim-go package) . 
Maybe we can use the same logic?

**Comment by zmb3** [comment]
vim-go approach: https://github.com/fatih/vim-go/blob/0b6d16c572316deafbcf4139cd44757c9349c91d/autoload/go/tool.vim#L67

Seems to be just inspecting the output for anything that looks like a filename/line number, which suffers from the drawbacks mentioned above.

**Comment by r03** [comment]
Maybe just make a hyperlink if a line matches something like this ? `(\w+_test\.go):(\d+)`
It doesn't cover everything, but probably the easiest to implement and covers most situations?
