### ISSUE TITLE
Enhancement: Custom/Additional Test Flags (textbox)

### ISSUE THREAD

**Issue by eduncan911** [joefitzgerald/go-plus#551]
### Description

Thank you for this awesome plugin!  

Could we get a textbox that would allow us to specify custom flags to pass into Tests?

Bonus points if this can be set on a Per-Project level.  But without a per-project config file (something I like about Atom and Go-Plus, vs VSCode that litters project files everywhere), I don't see how that could be possible.  

Justification:

I use options for `go test -cover -v` in the Plug In which gets me to about 78% code coverage with about 1100 lines of code in one very well tested project.

It says 78% because the I use glog which allows me to test for `verbose` level and if it is not set, it skips the performance hit of parsing formatted params.

    if glog.V(3) {
        glog.Infof("%s %s %+v\n", bus, name, event)
    }

Because I have lots of these, `-cover` does not run them because glog is set to V(0) on test runs.

I can get 100% coverage (oh yeah, 100% with 1100 lines of Go code!) with:

    $ go test -v -args -v 3 -logtostderr true

Note the `-args` flag that allows me to pass in additional flags to the testing package.  

NOTE: this enhancement may not make sense because of the way Golang parses flags: if you specify an unknown flag, the executable (and test) exits stating the unknown flag.

So, setting a global `-args -v 3` is not the smartest thing, unless the all of my projects uses glog (which no, they all don't use glog).  Hence the per-project justification.

Thoughts from others?

**Comment by antony66** [comment]
It would be useful to have an ability to add extra arguments to `go test` settings. For example, I write a bunch of microservices using beego.me framework. The way beego suggests to write tests is to have one single `tests/default_test.go` file to request application endpoints in a variety of ways. Running this way `-coverage` flag always shows 0% coverage because tests folder contains no actual code. To calculate coverage properly I always run `go test -v -coverprofile cover.out -coverpkg mypackage/models,mypackage/controllers`. So having an ability to set test flags per project would be even better.
