### ISSUE TITLE
Rename error: gorename: -to "gitlabClientFor(": not a valid identifier

### ISSUE THREAD

**Issue by BuZZ-dEE** [joefitzgerald/go-plus#581]
Tried to rename function `githubClientFor` in the `github.go` file from the [matrix-org/go-neb](https://github.com/matrix-org/go-neb/blob/master/src/github.com/matrix-org/go-neb/services/github/github.go) repository.

If I remove the `(` before renaming, I get this error: `gorename: can't find package containing /home/buzz-dee/Workspace/go-neb/src/github.com/matrix-org/go-neb/services/github/github.go`

**Comment by zmb3** [comment]
I'd like to help you, but first I need more information.  Especially relevant here is the value of your `GOPATH` environment variable.

In the future, please fill out the [issue template](https://github.com/joefitzgerald/go-plus/blob/master/.github/issue_template.md) instead of deleting it so that we have the information we need to help.

**Comment by zmb3** [comment]
After taking a closer look at that library, it seems it only supports `gb` builds.  This will prevent a lot of the Go-Plus features from working.

As a workaround, you could set your `GOPATH` to `/home/buzz-dee/Workspace/go-neb/`.  This should work as long as the `go-neb` project vendors all of its dependencies.
