### ISSUE TITLE
Guru highlighting colour makes identifier text hard to read

### ISSUE THREAD

**Issue by mkraft** [joefitzgerald/go-plus#621]
Guru highlighting makes the text of the highlighted identifier difficult to read with the following popular theme combination:

UI Theme: Atom Dark
Syntax Theme: Solarized Dark

![screen shot 2017-04-13 at 8 01 01 am](https://cloud.githubusercontent.com/assets/1149597/25003985/04c2db52-2020-11e7-9483-9fd71efc3f35.png)

It's a great feature that I want to keep enabled, but I also don't want to change my theme combination. Could we please make it configurable or change the colour for everyone?

**Comment by joefitzgerald** [comment]
This is actually a theme issue; we're just using the `selected` background color (https://github.com/joefitzgerald/go-plus/blob/5376e6800134852e7c0d4fa0287b889d19e39e03/styles/go-plus-guru.atom-text-editor.less#L4). https://github.com/atom/solarized-dark-syntax/pull/85 seems to describe how it *should* look with those combinations. The question is: why does yours look different?

**Comment by zmb3** [comment]
I'm noticing the same behavior with the solarized light syntax theme.

**Comment by zmb3** [comment]
It turns out `@background-color-selected` is for selections in the UI (tree-view, for example).  It is _not_ the background color for selected text.  For that, we should be using `@syntax-selection-color` from **syntax-variables.less**.

Current behavior (`@background-color-selected`):

<img width="487" alt="screen shot 2017-04-17 at 10 11 24 am" src="https://cloud.githubusercontent.com/assets/7527103/25095024/007464a0-2357-11e7-985d-c629cb817741.png">


With fix (`@syntax-selection-color`):

<img width="534" alt="screen shot 2017-04-17 at 10 12 22 am" src="https://cloud.githubusercontent.com/assets/7527103/25095015/f8094966-2356-11e7-88ea-257bd0c8dfc7.png">

Should be a super quick fix.  I'll get to it tonight if someone doesn't beat me to it.
