### ISSUE TITLE
Tests always run on save of a .go file since upgrade to 5.5.1

### ISSUE THREAD

**Issue by sgp** [joefitzgerald/go-plus#646]
### Description

Since upgrading from 5.4.0 to 5.5.1, go-plus always runs tests on save, even when the setting to do so is not enabled.

### Output from `atom -v && apm -v`

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.10.1

### Output From `go env`

GOARCH="amd64"
GOBIN="/Users/scott/Library/golang"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/scott/dev/pendo.io/pendo-appengine:/Users/scott/dev/pendo.io/goexternal"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### Steps to Reproduce

1. Go to the go-plus preferences and make sure "Run Tests on Save" checkbox is not ticked.
2. Save a `.go` source file.

### Expected Behavior

No tests are run if this checkbox isn't ticked.

### Actual Behavior

go-plus panel pops up with a `go test` run (which has failures, because I use App Engine).

**Comment by lloiser** [comment]
go-plus does _not_ run tests. It just compiles a test binary using `go test -c` on save. This is necessary to show you errors in your code in atom.
This was also done in 5.4.0 but with 5.5.0 go-plus has a "output panel" which is used to display all sorts of stuff, e.g. the fact that it compiles the test binary.

Unfortunately this cannot be turned off at the moment.

I don't have any experience with the app engine (goapp?) so I don't know what's necessary to get this working for you too. Can you give some insight or provide docs about testing with app engine. Maybe we have to detect this and do something else instead of `go test -c`.

**Comment by zmb3** [comment]
You're mistaken @lloiser - go-plus does run tests and there is an option to disable this. 

I will take a look into this regression. 

App engine has come up before. They do things a bit different and we've never had great support for that workflow.

**Comment by zmb3** [comment]
I tried to reproduce this and go-plus is _not_ running tests for me when test on save is disabled.

It is however compiling tests on save (as @lloiser mentioned above).  I don't know enough about app engine to understand whether this is what's causing your problem @sgp.

The `compiling tests with go test -c` message ends up staying in the output panel since there's no test output to replace it.  We can clean up that experience, but that's a separate issue.

@sgp can you please include a screenshot or a gif of the issue?  I'd like to see what things look like on your end.

**Comment by cention-sany** [comment]
I noticed the same issue also. It will be good there is an option to switch off this as it degrade my experience of using atom editor because it slow down the atom editor some how. I always need to disable and enable go-plus under Settings/Preference page which some how stop the go test -c compilation.

**Comment by suzerain** [comment]
FWIW, it's also running tests for me even though the checkbox is unchecked. This is on a fresh install: I only installed it today (August 11), and had never used it before.

**Comment by zmb3** [comment]
@suzerain I'd need to see it happen to be able to help.  Would you be able to record a screen capture or share your screen with me at some point?

**Comment by suzerain** [comment]
I can't share screen for security reasons, but it's quite straightforward: all of the checkboxes in the "tests" section are unchecked, and yet tests run in the go-plus window when it attempt to build.

The way I addressed this on my end was to dupe go-plus, and force the `hasTests` function in `builder.js` to return false. Now my copy never runs tests, of course, but that's what I needed right now.

**Comment by zmb3** [comment]
It sounds to me like you're seeing Go-plus *compile* your tests,  not run
them. Making hasTests return false would in fact disable compilation of
tests.  We always compile tests, even when we don't run them, so we can
show you build errors.

You aren't the first person to mistake this behavior for actually running
the tests. The window does say "running go test -c" and when it scrolls by
quickly it's easy to think that the tests are running. I will think about
ways to make this more obvious.

**Comment by suzerain** [comment]
Ahh that may well be. It's causing a compilation fail, then, because some of these tests don't compile unless they're in a certain environment. At any rate, it made it appear that I could never compile the actual code I wanted compiled, because the tests were failing to compile. So I guess blocking test compilation is in fact what I wanted.
