### ISSUE TITLE
Atom Docks

### ISSUE THREAD

**Issue by purpuregecko** [joefitzgerald/go-plus#661]
### Description
In Atom 1.17 [Docks was introduced](http://blog.atom.io/2017/05/16/atom-1-17.html).
What about usage it instead of yourself panel?
[go-debug](https://atom.io/packages/go-debug) already use it

### Steps to Reproduce
launch Atom >= 1.17 and go-plus.

**Comment by zmb3** [comment]
We've actually been playing with docks since before they were released.  There's a branch at https://github.com/joefitzgerald/go-plus/tree/jf-explore-docks.

Joe ran into a few areas where the docks support isn't quite ready to replace our panel.  I don't remember all of them, but one specific example I do recall is that there's no way to tell if your dock panel is currently visible (in order to avoid work that doesn't need to be done if the user isn't looking at the panel).

**Comment by mehcode** [comment]
> but one specific example I do recall is that there's no way to tell if your dock panel is currently visible

https://github.com/mehcode/linter-ui-plus/blob/master/lib/index.js#L206-L208

Not sure when that was added but it's working great for my package.
