### ISSUE TITLE
Autocomplete on unimported package does not work

### ISSUE THREAD

**Issue by irftokped** [joefitzgerald/go-plus#665]
First of all, thank you so much for this great plugin. It really ease my migration to golang (I'm new to this language)

### Description

The "Autocomplete on unimported package" does not seem to work

### Output from `atom -v && apm -v`

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4

### Output From `go env`

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/my-user-name/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build069586552=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### Steps to Reproduce

1. Installed atom
2. Install go-plus package
3. Let it install dependency
4. create a go file, and start typing some unimported package name (ex : sqlx, nap, redigo.redis)

### Expected Behavior

autocomplete-plus shows the recomended package from gocode

### Actual Behavior

the autocomplete didn't trigger at all.. when i manually import packages, the autocomplete feature works flawlessly.

I remember using it without problem a few weeks ago when i first installed atom and go-plus, but now it seems that it doesn't work anymore.
I've tried using atom-beta, and do a clean install of both (only installing package go-plus and git-plus) but it still won't autocomplete unimported packages. I've also tried restarting gocode, reinstalling gocode (with deleting the bin and src folder) and deleting the gocode cache, it still won't work

Due to this, I'm forced to try to use vscode for the time being, but i really don't like the ui of that, still, the unimported autocomplete does work there which is strange, because they're using gocode too.

**Comment by zmb3** [comment]
We're just using gocode's unimported package feature, which only works for standard library packages.

vscode actually does some extra work to extend this behavior to 3rd party packages.  If they get no suggestions, they add an import for you under the hood and run gocode a second time.  Maybe we can copy that behavior.

**Comment by iarief** [comment]
I see, if that could be implemented then it would be great. But how would the import be implemented? Does it need to scan the whole local GO_DIR for packages or does gocode already provide those?

**Comment by zmb3** [comment]
@iarief they use a tool called `gopkg` which scans `$GOPATH/pkg` to come up with a list of importable packages.  Then what they do is:

If the prefix was `.` and gocode returned 0 suggestions (potentially because of an unimported package), they look at what came before the `.` character, see if that's a valid package, transparently add an import to the code, and call gocode a second time.

**Comment by scbizu** [comment]
hmm.. Why go-plus drops the old auto-import way?

**Comment by lloiser** [comment]
@scbizu please check if the go-plus setting `Run format tool on save` is checked and the `Format tool` is `goimports`.

**Comment by scbizu** [comment]
![myconfig](http://i.imgur.com/JcSZcid.png)

@lloiser thx for your advice, I mean that I can not auto-import 3rd party just as @irftokped mentioned. So, I wonder if go-plus removes the old auto-import feature.(I am using vscode nowadays ,but I want to back atom(beta) again~)

**Comment by lloiser** [comment]
As long as `goimports` can find your 3rd party libs it can add import statements to your code on save.
Assume that you have `github.com/gorilla/mux` in your gopath you type the following code:
```go
package main

func main() {
    mux.NewRouter()
}
```
When you save the file it will automatically add the `import "github.com/gorilla/mux"` right after the `package main`.

What we _currently do not do_ (as @zmb3 said, see his comment https://github.com/joefitzgerald/go-plus/issues/665#issuecomment-320515766 above) is to add this `import "github.com/gorilla/mux"` hidden so that you get immediate autocomplete support when you type `mux.`

**Comment by scbizu** [comment]
It sounds like a useful feature~ It will be released in next go-plus 's release?
