### ISSUE TITLE
investigate atomlinter/linter possibly reducing surface area?

### ISSUE THREAD

**Issue by jokeyrhyme** [joefitzgerald/go-plus#67]
I've been using the Linter plugins for various other languages where available. I wonder if you've had a change to take a look at it: https://atom.io/packages/linter

The project strives to be a unified error highlighting system, so others can develop language-specific systems without needing to bother with the UI.

Is this definitely a no-go? Or is it something you'd accept a pull-request or something for?

**Comment by mishak87** [comment]
Could it be revisited? Linter has grown a bit and provides consistent and compact presentation for code related information (hints, warnings etc.) across languages and code checkers. *That said I have no idea if the API is mature enough or supports everything you would need to utilize it fully. Lot of linter plugins was created recently so that might be a good sign (over 70 in total).*

It would be useful if go-plus could detect installed Linter and use it for showing errors and lint information instead of showing it in own panel and using own gutter markers. It would be better to use unified interface instead of custom one just for single language.

Also showing information (lint, check, coverage) without having to save file first would be nice option to have.

For me the killer feature of go-plus package setup according to environment (support for gvm), most linters have to be set up manually which with multiple projects/go versions is really annoying.

![screen](https://cloud.githubusercontent.com/assets/276500/6032586/2d46b8f4-ac0b-11e4-8c51-a7ef8352f1c3.png)
*Personally I like how Linter presents information more then how go plus does it.*

**Comment by joefitzgerald** [comment]
The addition of package services reopens the possibility for this, particularly when apm installs required dependencies. 

It's early days, and I've been defining the initial pattern for inter-package dependencies via the new autocomplete-plus API. I do want Linter's API to evolve to use a similar approach, and to evolve Linter's display logic. @park9140 and I have been discussing the possibilities, and we'll eventually get there.

**Comment by joefitzgerald** [comment]
Also, I fully acknowledge that atom-message-panel is no longer an ideal solution. We've floated creating an `omnipanel` package that would have a union of the functionality of linter's and atom-message-panel's line, gutter, and panel displays plus some additional behavior found in omnisharp-atom and a few other packages.

**Comment by jokeyrhyme** [comment]
Is it worth reopening this issue then? Whether or not the implementation is for omnipanel or directly for linter?

**Comment by joefitzgerald** [comment]
Not at this time. It requires multiple things to occur - some of which may never occur - to be fulfilled. Just know that architecturally, I'm headed in that direction if things fall into place.
