### ISSUE TITLE
How to disable building?

### ISSUE THREAD

**Issue by Zamiell** [joefitzgerald/go-plus#674]
Thanks for the excellent plugin!

For my use-case, I want `go-plus` to run a format tool (`goimports`) on every save. But I don't want it to do any building, because my workflow uses the SFTP plugin - all the Go source files are on a remote server, and so building will always locally fail! So I'm constantly getting the panel popup flashing in my face every time I save a file.

How do I disable building??? There doesn't seem to be a check-box for this.
* I've unchecked "Run Tests On Save", and all of the other "Run Tests" related checkboxes, and that does not seem to stop building. I still get the panel popping up.
* Furthermore, I've added `--vendor, --disable-all, --json, .` to the gometalinter arguments box, and that doesn't seem to stop building either. I still get the panel popping up.

**Comment by zmb3** [comment]
There's no way to do so currently, but this seems like a perfectly valid workflow.

I'll throw in a quick config option for this.

**Comment by Zamiell** [comment]
Thank you for the quick response!!!!! <3

**Comment by zmb3** [comment]
Created #675 to address this.  If you're comfortable giving this a try locally and can provide feedback that'd be great.

@joefitzgerald what do you think?  Make sense?

**Comment by AlbinoGeek** [comment]
I need this, as otherwise `go-plus` always times out builds (after 60000) locking up my computer for up to a minute, for a file that builds manually in less than one second.  Something is broken with how `go-plus` calls the build.

**Comment by zmb3** [comment]
@AlbinoGeek it definitely sounds like something's not right with your environment.  Are you able to share your screen sometime and show me what things look like for you?

**Comment by Zamiell** [comment]
Thank you zmb3. Can you provide some short instructions on how to use this new feature?

**Comment by zmb3** [comment]
@Zamiell this isn't yet released, so if you want to try it out you'll have to install go-plus from source.  If you can wait, we should have a new release out soon.

If not, start by uninstalling go-plus (either from the UI, or via `apm uninstall go-plus`.  Then clone this repo, `cd` into it, run `apm install`, followed by `apm link`.  Restart Atom and you should see a new setting "Disable Compilation on Save" that you can uncheck.  Note: you may also want to uncheck "run tests on save" because if your build fails then your tests probably won't run either.

**Comment by joefitzgerald** [comment]
It’s acrjally much easier than that to work against master:

* `apm uninstall go-plus`
* `apm develop go-plus`
* `cd ~/github/go-plus`
* `apm link`
