### ISSUE TITLE
Feature: add setting for build timeout

### ISSUE THREAD

**Issue by luckcolors** [joefitzgerald/go-plus#679]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [x] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

When working with big source files it happens a lot on my machine that the build gets interrupted due to "build timed out after 10000 ms." as i have to save multiple times in order for the build to finally succed.
I haven't seen a setting for this in the Plugin's setting page.
So would it be possible to implement this? :)

### Output from `atom -v && apm -v`

```
Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.4
npm  3.10.10
node 6.9.5 ia32
python
git 2.13.3.windows.1
visual studio 2015
``` 

### Output From `go env`

``` 
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=F:\Gopath
set GORACE=
set GOROOT=D:\DevTools\Go
set GOTOOLDIR=D:\DevTools\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\LUCKCO~1\AppData\Local\Temp\go-build968550247=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```

### Steps to Reproduce

1. Save a souce file.
2. Build fails with timeout.
3. Restart from 1 until it succeds.

### Expected Behavior

The build should finish normally.

### Actual Behavior

Most of the times it gets aborted due to time out, this shouldn't happen or the timeout should be changeable.

**Comment by tirithen** [comment]
I have a similar problem, I use gorm and for testing I use a sqlite3 database (http://jinzhu.me/gorm/database.html#sqlite3). It seems like gorm brings an entire sqlite database engine because the build time for the test run is much greater than when I run the application as usual with MariaDB (also binary is larger with sqlite).

The setup still works though when I run the tests in the terminal, but with go-plus the build gets interrupted with the message "test timed out after 10000 ms." and I can't seem to find a setting for this. There are two timeout settings (Test timeout and Go Get timeout) but neither of those has any effect on the timeout that I assume is for the build.

The tests I run that does not include sqlite3 runs just fine and I can see the coverage i the editor which is super nice, just hoping for being able to do the same for the code parts that requires more compilation time.

**Comment by tirithen** [comment]
I realize that long build times are not optimal, but there is no need to kill the build before it's done, at least you should be able to set the timeout in that case. The speed of the machines that runs the build will also vary.

**Comment by luckcolors** [comment]
Yeah i totally agree with you.
Until this gets fixed the workaround i had to do is to change the constant: https://github.com/joefitzgerald/go-plus/blob/4270e4b5c8fbae751243cdea49d77fa60effdc99/lib/config/executor.js#L137

**Comment by pmaunz** [comment]
Please add an option for the timeout. Building and testing of packages including cgo code is slow and would really require the timeout to be increased.

**Comment by msama** [comment]
Same here, we use native libraries which unfortunately slow down tests.
