### ISSUE TITLE
Content of go file lost when saving file

### ISSUE THREAD

**Issue by ivoszz** [joefitzgerald/go-plus#695]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

After pasting a snippet to go file and trying to save file the content is lost and file is empty with zero length.

### Output from `atom -v && apm -v`

Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.5

### Output From `go env`

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ivoszz/go:/Users/ivoszz/workspace/golang"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kl/w_05c02x1cl7kvzy4r2xgvsc0000gn/T/go-build817271876=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### Steps to Reproduce

Prerequisities:
1. I have package server inside my $GOPATH with Server struct. This package is not related to the later code.

2. run format tool on save is on with goimports or goreturns (gofmt is obviously ok)

3. run tests on save is off

I tried to minimalize setup:

1. create new project (directory) inside your $GOPATH/src
2. create new file inside your new project (eg. bug.go)
3. paste this snippet (from gnatsd project):

package bug

func RunServerOnPort(port int) *server.Server {
	opts := gnatsd.DefaultTestOptions
	opts.Port = port
	return gnatsd.RunServer(&opts)
}

4. Save file (cmd-S)

### Expected Behavior

File is saved on disk with probably some error indicating that there are more packages that can satisfy import or with wrong import like running `goimports .` from commandline:
package bug

import "amonold/server"

func RunServerOnPort(port int) *server.Server {
	opts := gnatsd.DefaultTestOptions
	opts.Port = port
	return gnatsd.RunServer(&opts)
}

Detail inspection (-v) on command line indicates that there are 13 candidates for gnatsd and 26 candidates for server.

### Actual Behavior

After hitting Cmd-S the file is empty with zero length. I observed this behaviour for 4 times today during coding and lost at least 200 lines of code (fortunately test files). I never experience this behaviour before.

P.S.: Just discovered that after running goimports from commandline I am not able to reproduce the bug ( I never run goimports from commandline).The output is now the same like with goimports from commandline. But previously tested this example many times (with different editor options).

**Comment by lloiser** [comment]
Please open the developer tools in atom using `cmd-alt-i` and open the `Console` tab. 

Then save the file. Does anything appear in the log?

btw you are not the only one: https://github.com/joefitzgerald/go-plus/issues/409

**Comment by joefitzgerald** [comment]
I suspect the root cause here is an unexpected exit code (perhaps a 0 exit code) that is still associated with either an error or a no-op version of the `goimports` tool.

I would attempt to run the `goimports` tool manually to validate that it is functioning as expected. Then I would set a breakpoint ([here](https://github.com/joefitzgerald/go-plus/blob/e2277962328078400bbbc6be9710d8a9ac5f2575/lib/format/formatter.js#L172)) in the developer tools (described by @lloiser) to determine what exactly is happening.

**Comment by ivoszz** [comment]
Just the same error during today's refactoring session. I opened the developer tools, nothing special in console output. Only 1 error on the beginning complaining that I don't have `dlv` installed and 1 warning which I don't understand:

<embedded>:119170 IntersectionObserver.observe(target): target element is not a descendant of root.
TreeView @ <embedded>:119170

main.js [sm]:67 go-debug Failed to get "dlv" Error: Failed to get version of dlv:
  Exit code: 127
  Error: "spawn EACCES"
  Stderr: ""
  Stdout: ""
  Dlv path: "/Users/ivoszz/workspace/golang/bin/dlv"
    at delve-get.js [sm]:30
    at process._tickCallback (internal/process/next_tick.js:103)
(anonymous) @ main.js [sm]:67

Then there is a long list of test output during my session ending with:

Error: # amon/pkg/transport                                  <--- Ok output
./endpoint.go:94:13: undefined: heartbeatResp
./endpoint.go:100:12: undefined: commandReq
    at builder.js [sm]:53
orchestrator.js [sm]:79

Error: # amon/pkg/transport
./endpoint.go:100:12: undefined: commandReq
    at builder.js [sm]:53
    at process._tickCallback (internal/process/next_tick.js:103)    <----- ???????
orchestrator.js [sm]:79

Error: # amon/pkg/transport
./endpoint_test.go:134:69: undefined: commandReq
./endpoint_test.go:135:15: undefined: commandReq
    at builder.js [sm]:53
orchestrator.js [sm]:79

Error: # amon/pkg/transport
./endpoint_test.go:134:69: undefined: commandReq
./endpoint_test.go:135:15: undefined: commandReq
    at builder.js [sm]:53
orchestrator.js [sm]:79

Error: can't load package: package amon/pkg/transport:   <----- Empty file
endpoint_test.go:1:1: expected 'package', found 'EOF'
    at builder.js [sm]:53

I am confused with the line marked `????`. I can see it in some outputs (I guess it is test timeout?), but I didn't have timeout in last runs.
I will try to set breakpoint as you suggested. But definitively i didn't play with imports today. I only refactored some structs. And I always lost the content of test file, today when running tests on save.

**Comment by joefitzgerald** [comment]
OK so goimports is always called on save. If you have a reproducible loss of test file contents we should hop on a screen sharing session so that we can get eyes on it.

Are you open to a screen sharing session to figure this out? If so, please join the `#go-plus` channel in one of these Slack teams, and then direct message me your email address:

[![Slack](https://img.shields.io/badge/atom_slack-%23go--plus-blue.svg?style=flat)](https://atom-slack.herokuapp.com) [![Slack](https://img.shields.io/badge/gophers_slack-%23go--plus-blue.svg?style=flat)](https://gophersinvite.herokuapp.com)

**Comment by zmb3** [comment]
The repro steps listed above are not sufficient to reproduce the problem, and we haven't heard back in some time, so I'll close this out.  If you're open to troubleshooting with us feel free to reopen this.

**Comment by fjorgemota** [comment]
Hey.

This bug still happens here, but it's recoverable when you use CTRL+Z.

One thing that I've noted is when this issue occurs there are **always** a slowdown when saving the contents of the file. BUT it's correct to say that the bug is not reproducible always, so it's not as simple as saving code in a file and expecting it to simply happen (I have discorevered that because even saving the SAME CONTENT of the file again (after CTRL+Z) the saving occurs normally), the cases here seem totally random, with the only thing happening always before the bug occurs being the slowdown i've already mentioned.

Here is the content of `atom -v` and `apm -v`:

```$ atom -v
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ apm -v
apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python 2.7.12
git 2.15.1
```

And the output of `go env`:

```$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fernando"
GORACE=""
GOROOT="/home/fernando/.gimme/versions/go1.8.3.linux.amd64"
GOTOOLDIR="/home/fernando/.gimme/versions/go1.8.3.linux.amd64/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build133654185=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
``` 
Is there something I can do for helping debugging this bug for you? I do not consider screencasting because for many hours the issue simply do not happens, but sometimes it's really frequent. It's just not deterministic to know when the issue will happen or not.

**Comment by axife** [comment]
I have same issue. with goreturns and goimports. I think it is timeout. If goreturns formats source code longer then 10 seconds (or so) then atom kills process and replaces source with what killed process returned. It replaces with nothing and yes. It is often happens when computer is overloaded. Usually it formats files in less then a second.
