### ISSUE TITLE
GVM support?

### ISSUE THREAD

**Issue by runcom** [joefitzgerald/go-plus#74]
It would be nice to have https://github.com/moovweb/gvm support. GVM set the gopath to something like `/home/antonio/.gvm/pkgsets/go1.3.3/global` so you could derive the current go installation and tools

**Comment by mishak87** [comment]
Using Atom 1.1 when I have instance already running with another project launching
```sh
gvm use go1.5
# Now using version go1.5
export GOPATH="$(pwd):$GOPATH"
atom .
```
Seems like environment variables are not passed. When working with single project commands above are enough to get gvm working with go-plus.

Also I usually do first run without adding GOPATH to install tools globally. Would be handy to have list of commands for manual install as an alternative to automatic install.

**Comment by joefitzgerald** [comment]
When Atom is already running, any subsequent attempts to launch atom result in a new window being launched from the original process. So you're right, the environment for Windows 2...n will be ignored in favor of the environment for Window 1. There may be a workaround to this, but I'm not aware of it if there is.

**Comment by alecthomas** [comment]
Looking at [goexecutable.coffee](https://github.com/joefitzgerald/go-plus/blob/master/lib/goexecutable.coffee), it seems like go-plus doesn't inspect `GOROOT` (as per the [Go install documentation](https://golang.org/doc/install#tarball_non_standard)) to find the Go installation.? If it did so, I'm assuming gvm would "just work".

**Comment by mishak87** [comment]
GVM adds go binaries to `PATH` no need for `GOROOT`.

```
➜  ~  echo "$PATH"
/home/mishak/.gvm/bin:/home/mishak/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
➜  ~  gvm use go1.5
Now using version go1.5
➜  ~  echo "$PATH" 
/home/mishak/.gvm/pkgsets/go1.5/global/bin:/home/mishak/.gvm/gos/go1.5/bin:/home/mishak/.gvm/pkgsets/go1.5/global/overlay/bin:/home/mishak/.gvm/bin:/home/mishak/.gvm/bin:/home/mishak/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

**Comment by alecthomas** [comment]
I don't think that's relevant. GVM also updates GOROOT, and it is the "standard" way to locate the Go binaries, so supporting it would make all tools (including GVM) work.

**Comment by joefitzgerald** [comment]
GOROOT is required to be set when you put a runtime built for a standard location in a non-standard location. If you set the appropriate environment variables when building from source to your desired target location, GOROOT does not need to be set.

Regardless, go-plus doesn't care. You should ensure you launch atom from the terminal - in which your environment is set as you need - and things should just work. I agree I could add inspection of GOROOT to the detection logic, but in general the PATH should be used to specify the path to your desired runtime (and precedence among multiple installed runtimes).

You should remove the various paths from your configuration, check the option for environment overrides configuration, and make sure you launch atom from terminal or iterm2 instead of Dock/Finder/Spotlight/open.

**Comment by iDev0urer** [comment]
+1 on this. I am able to set my GOPATH manually in the settings, but I keep getting the following warning: `Warning: File [/home/chris/Documents/projects/personal/go/printf.go] does not reside within a "src" directory in your GOPATH [/home/chris/.gvm/pkgsets/go1.6rc1/global] - please review http://golang.org/doc/code.html#Workspaces`

**Comment by mjbrender** [comment]
I had trouble at first and then relaunched from terminal with no problem. Using gvm w/go1.5.3. Thanks @joefitzgerald!

**Comment by mishak87** [comment]
@iDev0urer workspaces are experimental feature in Go 1.5 in 1.6 they will be enabled.
https://tip.golang.org/doc/go1.6#go_command
