### ISSUE TITLE
Run format tool on save deletes 'import' command

### ISSUE THREAD

**Issue by CryptoD** [joefitzgerald/go-plus#764]
### Description

When "Run format tool on save" is on line of code is being deleted:
>package main
>import "fmt"

becomes:
>package main

Atom deletes the second line but leaves "package main" intact. "func main" and others are also intact. It seems that only 'import' command seems to be a problem.

### Steps to Reproduce

1. Open atom with go-plus on
2. Start a new file and begin coding

### Expected Behavior

I'm able to continue typing without my text being deleted

### Actual Behavior

Line:
> import "fmt"

is being deleted.

**Comment by lloiser** [comment]
Last paragraph of https://golang.org/ref/spec#Import_declarations:

> It is illegal for a package to import itself, directly or indirectly, or to **directly import a package without referring to any of its exported identifiers**.

It is actually a build error if you `import "fmt"` and do not use anything from the package then. 
The line is removed because `goimports` (the format tool) automatically removes unused package imports to avoid build errors.
Just add `_` in front of the import statement or the package name if you want to import a package but do not use it.

If this is not the case then please provide more information about your code and what formatting tool you use (see the settings of `go-plus`)

**Comment by CryptoD** [comment]
Changing `goimports` into `gofmt` in the go-plus ormat fsettings seems to solve the problem. _Import_ command is no longer deleted

**Comment by joefitzgerald** [comment]
@CryptoD just in case you're missing the point of `goimports`, that is the intended behavior. You do *not* need to explicitly add an import. You can just type `fmt.Println("hello, world!")`, and the `import "fmt"` import will be added for you automatically. Additionally, if you *do* chose to manually add the import line, just don't save the file prior to using the import.

Also, you might want to survey some experienced gophers and see who uses `goimports` vs. who uses `gofmt`.

**Comment by CryptoD** [comment]
@joefitzgerald I was not aware of such feature of `goimports`, thanks for clarifying! Makes more sense now.
